name: .NET Core

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.301
    - name: Install dependencies
      run: dotnet restore "ConsoleUI/BetterConsoleApp/ConsoleUI/ConsoleUI.csproj"
    - name: Build
      run: dotnet build "ConsoleUI/BetterConsoleApp/ConsoleUI/ConsoleUI.csproj" --configuration Release --no-restore
    - name: Test
      run: dotnet test "ConsoleUI/BetterConsoleApp/ConsoleUI.Test/ConsoleUI.Test.csproj" --no-restore --verbosity normal
